version: '3.8'

services:
  capital-gains:
    build:
      context: ./capital-gains-service
      dockerfile: Dockerfile
    container_name: capital-gains
    ports:
      - "5003:8080"
    expose:
    - 8080
    depends_on:
      - mongodb
    volumes:
      - ./common:/app/common
    restart: always

  stocks1:
    build:
      context: ./stocks-service
    container_name: stocks1
    ports:
      - "5001:8000"
    expose:
    - 8000
    environment:
      COLLECTION: stocks1
    depends_on:
      - mongodb
    volumes:
      - ./common:/app/common
    restart: always

  stocks2:
    build:
      context: ./stocks-service
    container_name: stocks2
    ports:
      - "5002:8000"
    expose:
    - 8000
    environment:
      COLLECTION: stocks2
    depends_on:
      - mongodb
    volumes:
      - ./common:/app/common
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: